image: "ruby:2.6"

before_script:
  - ruby -v  # Print out ruby version for debugging
  - bundle install -j $(nproc) --path vendor  # Install dependencies into ./vendor/ruby

cache:
  paths:
    - vendor/ruby

test:
  script:
    - rspec

docs:
  script:
    - rspec doc:generate