image: "ruby:2.6"

stages:
  - test
  - deploy

variables:
  os: linux
  arch: amd64
  version: v3.3.2

before_script:
  - wget https://github.com/bukalapak/snowboard/releases/download/${version}/snowboard-${version}.${os}-${arch}.tar.gz
  - tar -zxvf snowboard-${version}.${os}-${arch}.tar.gz
  - rm snowboard-${version}.${os}-${arch}.tar.gz
  - ./snowboard -v
  - ruby -v
  - which ruby
  - gem install bundler
  - bundle install --jobs $(nproc) --path vendor

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby
    - doc/api
    - public/

test:
  stage: test
  script:
    - bundle exec rake build:docs
    - ./snowboard html -o public/index.html doc/index.apib

deploy:
  stage: deploy
  script:
    - rm ./snowboard
    - ls -l doc/api/
    - gem install dpl
    - dpl --no-cleanup --skip-cleanup --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY

#release:
#  stage: release
#  script:
#    - git config --global user.name "${GITHUB_USER_NAME}"
#    - git config --global user.email "${GITHUB_USER_EMAIL}"
#    - git add --all
#    - git commit -m "GitLab Runner Push"
#    - git push http://${GITHUB_USERNAME}:${PERSONAL_ACCESS_TOKEN}@github.com/tkrause/SoccerApi.git HEAD:production
