image: "ruby:2.6"

stages:
  - test
  - deploy

before_script:
  - ruby -v
  - which ruby
  - gem install bundler
  - bundle install --jobs $(nproc) --path vendor

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby
    - doc/api

test:
  stage: test
  script:
    - bundle exec rake docs:generate

deploy:
  stage: deploy
  script:
    - ls -l doc/api/
    - gem install dpl
    - dpl --no-cleanup --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY

#release:
#  stage: release
#  script:
#    - git config --global user.name "${GITHUB_USER_NAME}"
#    - git config --global user.email "${GITHUB_USER_EMAIL}"
#    - git add --all
#    - git commit -m "GitLab Runner Push"
#    - git push http://${GITHUB_USERNAME}:${PERSONAL_ACCESS_TOKEN}@github.com/tkrause/SoccerApi.git HEAD:production
