image: "ruby:2.6"

stages:
  - build
  - test
  - docs

build:
  stage: build
  script:
    - ruby -v
    - bundle install -j $(nproc) --path vendor

test:
  stage: test
  script:
    - rspec

docs:
  stage: docs
  script:
    - rspec doc:generate

cache:
  paths:
    - vendor/ruby

