image: "ruby:2.6"

stages:
  - test
  - deploy

before_script:
  - ruby -v
  - which ruby
  - gem install bundler
  - bundle install --jobs $(nproc) --path vendor

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby
    - doc/api

test:
  stage: deploy
  script:
    - rspec
    - rspec doc:generate
#
#release:
#  stage: release
#  script:
#    - git config --global user.name "${GITHUB_USER_NAME}"
#    - git config --global user.email "${GITHUB_USER_EMAIL}"
#    - git add --all
#    - git commit -m "GitLab Runner Push"
#    - git push http://${GITHUB_USERNAME}:${PERSONAL_ACCESS_TOKEN}@github.com/tkrause/SoccerApi.git HEAD:production
